# 브로드 캐스팅

In [2]:
import numpy as np

In [ ]:
# 넘파이 배열의 차원과 모양에 대한 코드
a1 = np.linspace(1, 12, 12).reshape((3, 4)) 
a2 = np.arange(1, 5) # [1, 2, 3, 4]
a3 = a2.reshape((4, 1)) # [[1] [2] [3] [4]]
a4 = a1.reshape((3, 1, 4))
print(a1)
print(a2)
print(a3)
print(a4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]


In [ ]:
# 브로드 캐스팅을 이용한 배열 연산
print(a1 + a2)  # 브로드캐스팅: a2가 a1의 각 행에 더해짐
print((a1 + a2).shape)
print(a2 + a3)  # 브로드캐스팅: a3가 a2의 각 열에 더해짐
print((a2 + a3).shape)
print(a1 + a4)  # 브로드캐스팅: a4가 a1의 각 행에 더해짐
print((a1 + a4).shape)
# 배열 보는 법: 맨 뒤에 숫자부터 가로, 세로, 깊이 순

[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]
 [10. 12. 14. 16.]]
(3, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
(4, 4)
[[[ 2.  4.  6.  8.]
  [ 6.  8. 10. 12.]
  [10. 12. 14. 16.]]

 [[ 6.  8. 10. 12.]
  [10. 12. 14. 16.]
  [14. 16. 18. 20.]]

 [[10. 12. 14. 16.]
  [14. 16. 18. 20.]
  [18. 20. 22. 24.]]]
(3, 3, 4)


## 인덱싱

In [50]:
a1 = np.arange(1, 10 + 1) ** 2 # [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
a2 = a1[2:9] # [9, 16, 25, 36, 49, 64, 81] : 얕은 복사
print(a1, a2)
a1[3] = a1[1] + a1[2] # 원소의 변경
print(a1) # [1, 4, 9, 13, 25, 36, 49, 64, 81, 100]
a2[:5:2] = 10_000 # 슬라이스의 변경
# for i in range(len(a1)):
#     print(a1[(i + 1) * -1], end=", ") # 역순으로 출력
print(a1[::-1]) # 역순으로 출력 - 위의 for문과 동일
print()

[  1   4   9  16  25  36  49  64  81 100] [ 9 16 25 36 49 64 81]
[  1   4   9  13  25  36  49  64  81 100]
[  100    81    64 10000    36 10000    13 10000     4     1]



In [51]:
a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64) 
a2 = a1[:, 1::2, :3]  # 슬라이스를 이용한 배열 추출 - 얕은 복사

print("a1\n", a1)
print("a2\n",a2)
a2[1, ...] = -1 

print("a1\n",a1)
for ar in a2:
    print("ar\n",ar)

a1
 [[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]]
a2
 [[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [4 5 6]]]
a1
 [[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]
  [ 4  5  6  7]]

 [[ 1  2  3  4]
  [-1 -1 -1  5]
  [ 3  4  5  6]
  [-1 -1 -1  7]
  [ 5  6  7  8]]]
ar
 [[1 2 3]
 [3 4 5]]
ar
 [[-1 -1 -1]
 [-1 -1 -1]]


In [52]:
# vstack
a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64) 
a2 = np.arange(1, a1.size/2+1).reshape(1, 5, 4) * 10 
print("a1\n", a1)
print("a2\n", a2)

a1
 [[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]]
a2
 [[[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]


In [53]:
a3 = np.vstack((a1[0, ...], a2[0, ...])) # a1의 첫 번째 슬라이스와 a2를 수직으로 쌓음 - shape 안 맞추면 오류 발생
print("a3\n", a3)
a4 = np.hstack((a1[0, ...], a2[0, ...])) # a1의 첫 번째 슬라이스와 a2를 수평으로 쌓음
print("a4\n", a4)
a5 = np.concatenate((a1, a2), 0) # a1과 a2를 수직으로 쌓음
print("a5\n", a5)
a6 = np.concatenate((a1[0, ...], a2[0, ...]), 0)  # hstack
a7 = np.concatenate((a1[0, ...], a2[0, ...]), 1)  # vstack
print("a6\n", a6)
print("a7\n", a7)

a3
 [[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]
 [170. 180. 190. 200.]]
a4
 [[  0.   1.   2.   3.  10.  20.  30.  40.]
 [  1.   2.   3.   4.  50.  60.  70.  80.]
 [  2.   3.   4.   5.  90. 100. 110. 120.]
 [  3.   4.   5.   6. 130. 140. 150. 160.]
 [  4.   5.   6.   7. 170. 180. 190. 200.]]
a5
 [[[  0.   1.   2.   3.]
  [  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]]

 [[  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]
  [  5.   6.   7.   8.]]

 [[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]
a6
 [[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100

In [54]:
# split
a = np.arange(24).reshape(3, 2, 4) 
# b1, b2, b3 = np.vsplit(a, 3)  # 얕은 복사
# b4, b5 = np.hsplit(a, 2)  # 얕은 복사
b1 = a[0, ...] 
b2 = a[1, ...] 
b3 = a[2, ...] 
b4 = a[:, 0, :] 
b5 = a[:, 1, :]

print(a)
b1[...] = 100
print(b1, b2, b3, b4, b5, sep="\n\n\n")
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[100 100 100 100]
 [100 100 100 100]]


[[ 8  9 10 11]
 [12 13 14 15]]


[[16 17 18 19]
 [20 21 22 23]]


[[100 100 100 100]
 [  8   9  10  11]
 [ 16  17  18  19]]


[[100 100 100 100]
 [ 12  13  14  15]
 [ 20  21  22  23]]
[[[100 100 100 100]
  [100 100 100 100]]

 [[  8   9  10  11]
  [ 12  13  14  15]]

 [[ 16  17  18  19]
  [ 20  21  22  23]]]


In [55]:
a1 = np.arange(1, 5) # 1부터 4까지의 정수를 포함하는 1차원 배열 생성
a2 = np.arange(1, 7).reshape((2, 3)) # 1부터 6까지의 정수를 2행 3열의 2차원 배열로 생성
a3 = np.linspace(10, 120, 12).reshape((3, 2, 2)) # 10부터 120까지 12개의 균일한 간격의 숫자를 3x2x2의 3차원 배열로 생성
b1 = a1.T  # 1차원 배열 a1을 전치
b2 = a2.transpose() # 2차원 배열 a2를 전치
b2[0] = 100 # 전치된 b2의 첫 번째 행(원본 a2의 첫 번째 열)을 100으로 변경
b3 = np.transpose(a3) # 3차원 배열 a3를 전치

# print(a1, a2, a3, b1, b2, b3, sep="\n\n\n")
print("a1\n", a1)
print("a2\n", a2)
print("a3\n", a3)
print("b1\n", b1)
print("b2\n", b2)
print("b3\n", b3)

a1
 [1 2 3 4]
a2
 [[100   2   3]
 [100   5   6]]
a3
 [[[ 10.  20.]
  [ 30.  40.]]

 [[ 50.  60.]
  [ 70.  80.]]

 [[ 90. 100.]
  [110. 120.]]]
b1
 [1 2 3 4]
b2
 [[100 100]
 [  2   5]
 [  3   6]]
b3
 [[[ 10.  50.  90.]
  [ 30.  70. 110.]]

 [[ 20.  60. 100.]
  [ 40.  80. 120.]]]


---

### 연산 과정

NumPy 배열을 생성  
이 배열들에 대해 전치(Transpose) 연산을 수행  
전치된 배열의 특정 요소를 변경할 때 원본 배열에 미치는 영향 확인

**1. `a1 = np.arange(1, 5)` 연산:**
* **목표:** 1부터 4까지의 정수를 포함하는 1차원 NumPy 배열을 생성합니다.
* **과정:** `np.arange(1, 5)` 함수는 `start=1` (포함)부터 `stop=5` (미포함)까지 1씩 증가하는 정수를 생성하여 배열을 만듭니다.
* **결과 `a1`:**
    ```
    [1 2 3 4]
    ```
* **`a1`의 형태(shape):** `(4,)`

**2. `a2 = np.arange(1, 7).reshape((2, 3))` 연산:**
* **목표:** 1부터 6까지의 정수를 포함하는 2행 3열의 2차원 NumPy 배열을 생성합니다.
* **과정:**
    * `np.arange(1, 7)`은 1부터 6까지의 정수 배열 `[1 2 3 4 5 6]`을 생성합니다.
    * `.reshape((2, 3))` 메서드는 이 1차원 배열을 2행 3열의 2차원 배열로 재구성합니다. 요소들은 행 우선(row-major) 순서로 채워집니다.
* **결과 `a2`:**
    ```
    [[1 2 3]
     [4 5 6]]
    ```
* **`a2`의 형태(shape):** `(2, 3)`

**3. `a3 = np.linspace(10, 120, 12).reshape((3, 2, 2))` 연산:**
* **목표:** 10부터 120까지의 범위에서 12개의 균일한 간격의 숫자를 포함하는 3x2x2 형태의 3차원 NumPy 배열을 생성합니다.
* **과정:**
    * `np.linspace(10, 120, 12)`는 `start=10`, `stop=120`, `num=12`로 설정되어 10과 120을 포함하여 그 사이를 12등분한 숫자를 1차원 배열로 생성합니다.
    * `.reshape((3, 2, 2))` 메서드는 이 1차원 배열을 3개의 2x2 행렬로 구성된 3차원 배열로 재구성합니다.
* **결과 `a3`:**
    ```
    [[[ 10.  20.]
      [ 30.  40.]]

     [[ 50.  60.]
      [ 70.  80.]]

     [[ 90. 100.]
      [110. 120.]]]
    ```
* **`a3`의 형태(shape):** `(3, 2, 2)`

**4. `b1 = a1.T` 연산:**
* **목표:** 1차원 배열 `a1`을 전치합니다.
* **과정:** NumPy에서 1차원 배열의 `.T` (transpose) 속성은 배열의 형태를 변경하지 않습니다. 즉, 1차원 배열은 전치해도 동일한 1차원 배열입니다.
* **결과 `b1`:**
    ```
    [1 2 3 4]
    ```
* **`b1`의 형태(shape):** `(4,)`

**5. `b2 = a2.transpose()` 연산:**
* **목표:** 2차원 배열 `a2`를 전치합니다.
* **과정:** `a2.transpose()` 메서드는 `a2`의 행과 열을 바꿉니다. `a2`가 `(2, 3)` 형태이므로, 전치된 `b2`는 `(3, 2)` 형태가 됩니다. NumPy의 `.transpose()` 또는 `.T`는 기본적으로 **원본 배열의 뷰(view)를 반환**합니다. 이는 `b2`가 `a2`의 데이터를 직접 참조한다는 의미입니다.
* **`b2`의 초기 결과 (변경 전):**
    ```
    [[1 4]
     [2 5]
     [3 6]]
    ```
* **`b2`의 형태(shape):** `(3, 2)`

**6. `b2[0] = 100` 연산:**
* **목표:** 전치된 배열 `b2`의 첫 번째 행에 `100`을 대입합니다.
* **과정:** `b2[0]`은 `b2`의 첫 번째 행 `[1 4]`를 참조합니다. 여기에 `100`을 대입하면, Python의 브로드캐스팅 규칙에 따라 `b2`의 첫 번째 행의 모든 요소가 `100`으로 변경됩니다.
    * `b2[0]`은 `b2`의 첫 번째 행인 `[1 4]`를 의미합니다.
    * `b2[0] = 100`은 `b2[0]`의 모든 요소를 `100`으로 만듭니다. 즉 `[1 4]`가 `[100 100]`이 됩니다.
* **`b2`의 변경 후 결과:**
    ```
    [[100 100]
     [  2   5]
     [  3   6]]
    ```
* **`a2`에 미치는 영향:** `b2`가 `a2`의 뷰였기 때문에, `b2`의 변경은 원본 `a2`에도 영향을 미칩니다. `b2`의 첫 번째 행은 원본 `a2`의 첫 번째 열에 해당합니다. 따라서 `a2`의 첫 번째 열 요소들이 `100`으로 변경됩니다.
* **`a2`의 최종 상태:**
    ```
    [[100   2   3]
     [100   5   6]]
    ```

**7. `b3 = np.transpose(a3)` 연산:**
* **목표:** 3차원 배열 `a3`를 전치합니다.
* **과정:** `np.transpose()` 함수는 기본적으로 축의 순서를 역순으로 변경하여 전치합니다. `a3`의 원래 축 순서는 `(0, 1, 2)` (깊이, 행, 열)입니다. 전치되면 축 순서가 `(2, 1, 0)`으로 변경됩니다. 즉, `a3`의 세 번째 차원(열)이 첫 번째 차원(깊이)으로, 첫 번째 차원(깊이)이 세 번째 차원(열)으로 오게 됩니다.
* **결과 `b3`:**
    ```
    [[[ 10.  50.  90.]
      [ 30.  70. 110.]]

     [[ 20.  60. 100.]
      [ 40.  80. 120.]]]
    ```
* **`b3`의 형태(shape):** `(2, 2, 3)` (원래 `(3, 2, 2)`에서 축 0과 축 2가 바뀜)

---

**최종 출력 결과**

```
# a1
[1 2 3 4]


# a2 (b2[0] = 100에 의해 변경됨)
[[100   2   3]
 [100   5   6]]


# a3
[[[ 10.  20.]
  [ 30.  40.]]

 [[ 50.  60.]
  [ 70.  80.]]

 [[ 90. 100.]
  [110. 120.]]]


# b1 (a1.T)
[1 2 3 4]


# b2 (a2.transpose(), 이후 b2[0]=100으로 변경됨)
[[100 100]
 [  2   5]
 [  3   6]]


# b3 (np.transpose(a3))
[[[ 10.  50.  90.]
  [ 30.  70. 110.]]

 [[ 20.  60. 100.]
  [ 40.  80. 120.]]]
```

In [56]:
a1 = np.array([[2, -1, 5], [-5, 2, 2], [2, 1, 3]])
a2 = np.array([[0, -1, 0], [1, 0, 1], [1, 1, 0]])
a3 = np.array([1, -1, 1])
a4 = np.array([1, 0, 1]).reshape((3, 1))

b1 = np.dot(a1, a2)
b2 = a1.dot(a3)
b3 = a1 @ a4

# print(a1, a2, a3, a4, b1, b2, b3, sep="\n\n\n")
print("\na1\n", a1)
print("\na2\n", a2)
print("\na3\n", a3)
print("\na4\n", a4)
print("\nb1\n", b1)
print("\nb2\n", b2)
print("\nb3\n", b3)


a1
 [[ 2 -1  5]
 [-5  2  2]
 [ 2  1  3]]

a2
 [[ 0 -1  0]
 [ 1  0  1]
 [ 1  1  0]]

a3
 [ 1 -1  1]

a4
 [[1]
 [0]
 [1]]

b1
 [[ 4  3 -1]
 [ 4  7  2]
 [ 4  1  1]]

b2
 [ 8 -5  4]

b3
 [[ 7]
 [-3]
 [ 5]]


b1, b2, b3에 대한 계산 과정을 구성하는 수식들을 아래에 전체 출력

---

### 연산 과정 수식

**1. `b1 = np.dot(a1, a2)` 연산 수식:**

`a1` (3x3 행렬)과 `a2` (3x3 행렬)의 행렬 곱셈 `b1`은 다음과 같이 계산됩니다.

$$
b1 = \begin{pmatrix}
2 & -1 & 5 \\
-5 & 2 & 2 \\
2 & 1 & 3
\end{pmatrix}
\times
\begin{pmatrix}
0 & -1 & 0 \\
1 & 0 & 1 \\
1 & 1 & 0
\end{pmatrix}
$$

각 요소 $b1_{ij}$는 $a1$의 $i$번째 행과 $a2$의 $j$번째 열의 내적으로 계산됩니다.

* $b1_{00} = (a1[0, 0] \times a2[0, 0]) + (a1[0, 1] \times a2[1, 0]) + (a1[0, 2] \times a2[2, 0])$  
    $ = (2 \times 0) + (-1 \times 1) + (5 \times 1)$  
    $ = 0 - 1 + 5 = 4$  
* $b1_{01} = (a1[0, 0] \times a2[0, 1]) + (a1[0, 1] \times a2[1, 1]) + (a1[0, 2] \times a2[2, 1])$  
    $ = (2 \times -1) + (-1 \times 0) + (5 \times 1)$  
    $ = -2 + 0 + 5 = 3$  
* $b1_{02} = (a1[0, 0] \times a2[0, 2]) + (a1[0, 1] \times a2[1, 2]) + (a1[0, 2] \times a2[2, 2])$  
    $ = (2 \times 0) + (-1 \times 1) + (5 \times 0)$  
    $ = 0 - 1 + 0 = -1$  
* $b1_{10} = (a1[1, 0] \times a2[0, 0]) + (a1[1, 1] \times a2[1, 0]) + (a1[1, 2] \times a2[2, 0])$  
    $ = (-5 \times 0) + (2 \times 1) + (2 \times 1)$  
    $ = 0 + 2 + 2 = 4$  
* $b1_{11} = (a1[1, 0] \times a2[0, 1]) + (a1[1, 1] \times a2[1, 1]) + (a1[1, 2] \times a2[2, 1])$  
    $ = (-5 \times -1) + (2 \times 0) + (2 \times 1)$  
    $ = 5 + 0 + 2 = 7$  
* $b1_{12} = (a1[1, 0] \times a2[0, 2]) + (a1[1, 1] \times a2[1, 2]) + (a1[1, 2] \times a2[2, 2])$  
    $ = (-5 \times 0) + (2 \times 1) + (2 \times 0)$  
    $ = 0 + 2 + 0 = 2$  
* $b1_{20} = (a1[2, 0] \times a2[0, 0]) + (a1[2, 1] \times a2[1, 0]) + (a1[2, 2] \times a2[2, 0])$  
    $ = (2 \times 0) + (1 \times 1) + (3 \times 1)$  
    $ = 0 + 1 + 3 = 4$  
* $b1_{21} = (a1[2, 0] \times a2[0, 1]) + (a1[2, 1] \times a2[1, 1]) + (a1[2, 2] \times a2[2, 1])$  
    $ = (2 \times -1) + (1 \times 0) + (3 \times 1)$  
    $ = -2 + 0 + 3 = 1$  
* $b1_{22} = (a1[2, 0] \times a2[0, 2]) + (a1[2, 1] \times a2[1, 2]) + (a1[2, 2] \times a2[2, 2])$  
    $ = (2 \times 0) + (1 \times 1) + (3 \times 0)$  
    $ = 0 + 1 + 0 = 1$  

따라서 $b1$의 결과는:
$$
b1 = \begin{pmatrix}
4 & 3 & -1 \\
4 & 7 & 2 \\
4 & 1 & 1
\end{pmatrix}
$$

---

**2. `b2 = a1.dot(a3)` 연산 수식:**

`a1` (3x3 행렬)과 `a3` (1차원 배열, 길이가 3)의 행렬-벡터 곱셈 `b2`는 다음과 같이 계산됩니다. `a3`는 열 벡터로 간주됩니다.

$$
b2 = \begin{pmatrix}
2 & -1 & 5 \\
-5 & 2 & 2 \\
2 & 1 & 3
\end{pmatrix}
\times
\begin{pmatrix}
1 \\
-1 \\
1
\end{pmatrix}
$$

각 요소 $b2_{i}$는 $a1$의 $i$번째 행과 $a3$ 벡터의 내적으로 계산됩니다.

* $b2_{0} = (a1[0, 0] \times a3[0]) + (a1[0, 1] \times a3[1]) + (a1[0, 2] \times a3[2])$  
    $ = (2 \times 1) + (-1 \times -1) + (5 \times 1)$  
    $ = 2 + 1 + 5 = 8$  
* $b2_{1} = (a1[1, 0] \times a3[0]) + (a1[1, 1] \times a3[1]) + (a1[1, 2] \times a3[2])$  
    $ = (-5 \times 1) + (2 \times -1) + (2 \times 1)$  
    $ = -5 - 2 + 2 = -5$  
* $b2_{2} = (a1[2, 0] \times a3[0]) + (a1[2, 1] \times a3[1]) + (a1[2, 2] \times a3[2])$  
    $ = (2 \times 1) + (1 \times -1) + (3 \times 1)$  
    $ = 2 - 1 + 3 = 4$  

따라서 $b2$의 결과는:
$$
b2 = \begin{pmatrix}
8 \\
-5 \\
4
\end{pmatrix}
$$
(Numpy는 1차원 배열로 출력: `[ 8 -5  4]`)

---

**3. `b3 = a1 @ a4` 연산 수식:**

`a1` (3x3 행렬)과 `a4` (3x1 열 벡터)의 행렬 곱셈 `b3`는 다음과 같이 계산됩니다.

$$
b3 = \begin{pmatrix}
2 & -1 & 5 \\
-5 & 2 & 2 \\
2 & 1 & 3
\end{pmatrix}
\times
\begin{pmatrix}
1 \\
0 \\
1
\end{pmatrix}
$$

각 요소 $b3_{ij}$는 $a1$의 $i$번째 행과 $a4$의 $j$번째 열의 내적으로 계산됩니다. `a4`는 단일 열이므로 $j=0$만 해당합니다.

* $b3_{00} = (a1[0, 0] \times a4[0, 0]) + (a1[0, 1] \times a4[1, 0]) + (a1[0, 2] \times a4[2, 0])$  
    $ = (2 \times 1) + (-1 \times 0) + (5 \times 1)$  
    $ = 2 + 0 + 5 = 7$  
* $b3_{10} = (a1[1, 0] \times a4[0, 0]) + (a1[1, 1] \times a4[1, 0]) + (a1[1, 2] \times a4[2, 0])$  
    $ = (-5 \times 1) + (2 \times 0) + (2 \times 1)$  
    $ = -5 + 0 + 2 = -3$  
* $b3_{20} = (a1[2, 0] \times a4[0, 0]) + (a1[2, 1] \times a4[1, 0]) + (a1[2, 2] \times a4[2, 0])$  
    $ = (2 \times 1) + (1 \times 0) + (3 \times 1)$  
    $ = 2 + 0 + 3 = 5$  

따라서 $b3$의 결과는:
$$
b3 = \begin{pmatrix}
7 \\
-3 \\
5
\end{pmatrix}
$$

In [74]:
a1 = np.random.randint(10, size=(3, 3))
a2 = np.linalg.inv(a1)
a3 = np.array([[2, 3], [5, 6]])
a4 = np.array([4, 7])
# a5 = np.linalg.solve(a3, a4)
a5 = np.linalg.inv(a3).dot(a4) # 위와 동일

print("\na1\n", a1)
print("\na2\n", a2)
print("\na3\n", a3)
print("\na4\n", a4)
print("\na5\n", a5)


a1
 [[4 0 1]
 [0 4 1]
 [7 8 2]]

a2
 [[ 0.         -0.28571429  0.14285714]
 [-0.25       -0.03571429  0.14285714]
 [ 1.          1.14285714 -0.57142857]]

a3
 [[2 3]
 [5 6]]

a4
 [4 7]

a5
 [-1.  2.]


In [ ]:
# 생성하고 배열에 대해 .npz확장자로 저장
a1 = np.arange(360 + 1)
# a2 = np.sin(a1* np.pi/180 )
a2 = np.sin(np.radians(a1))
print(a2)

np.savez_compressed("sin_sample", x=a1, y=a2)

[ 0.00000000e+00  1.74524064e-02  3.48994967e-02  5.23359562e-02
  6.97564737e-02  8.71557427e-02  1.04528463e-01  1.21869343e-01
  1.39173101e-01  1.56434465e-01  1.73648178e-01  1.90808995e-01
  2.07911691e-01  2.24951054e-01  2.41921896e-01  2.58819045e-01
  2.75637356e-01  2.92371705e-01  3.09016994e-01  3.25568154e-01
  3.42020143e-01  3.58367950e-01  3.74606593e-01  3.90731128e-01
  4.06736643e-01  4.22618262e-01  4.38371147e-01  4.53990500e-01
  4.69471563e-01  4.84809620e-01  5.00000000e-01  5.15038075e-01
  5.29919264e-01  5.44639035e-01  5.59192903e-01  5.73576436e-01
  5.87785252e-01  6.01815023e-01  6.15661475e-01  6.29320391e-01
  6.42787610e-01  6.56059029e-01  6.69130606e-01  6.81998360e-01
  6.94658370e-01  7.07106781e-01  7.19339800e-01  7.31353702e-01
  7.43144825e-01  7.54709580e-01  7.66044443e-01  7.77145961e-01
  7.88010754e-01  7.98635510e-01  8.09016994e-01  8.19152044e-01
  8.29037573e-01  8.38670568e-01  8.48048096e-01  8.57167301e-01
  8.66025404e-01  8.74619

In [79]:
# .npz확장자로 저장된 배열에 대해 로드
a3 = np.load("sin_sample.npz")
print(a3["x"])
print(a3["y"])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [80]:
# A[n], B[m]에 대하여 A의 n번째, B의 m-1번째의 요소의 수가 같다면 dot product가 가능함
import numpy as np

A = np.random.randn(2, 3, 4, 1, 3, 9)
B = np.random.randn(7, 4, 9, 3)
C = np.dot(A, B) # (2, 3, 5, 6)
print(C.shape) # (2, 3, 5, 6)

(2, 3, 4, 1, 3, 7, 4, 3)
