In [7]:
import pandas as pd

wine = pd.read_csv("/home/aa/Big2025/ml_dl_python/data/wine_csv_data.csv")

In [8]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [9]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=42
)

In [10]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
import numpy as np

rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(
    rf, train_input, train_target, return_train_score=True, n_jobs=-1
)
print(np.mean(scores["train_score"]), np.mean(scores["test_score"]))

0.9973541965122431 0.8905151032797809


In [11]:
rf.fit(train_input, train_target)
print(rf.classes_)
print(rf.feature_importances_)

[0. 1.]
[0.23167441 0.50039841 0.26792718]


In [12]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


In [13]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(
    et, train_input, train_target, return_train_score=True, n_jobs=-1
)

print(np.mean(scores["train_score"]), np.mean(scores["test_score"]))

0.9974503966084433 0.8887848893166506


In [14]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


In [15]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(
    gb, train_input, train_target, return_train_score=True, n_jobs=-1
)

print(np.mean(scores["train_score"]), np.mean(scores["test_score"]))

0.8881086892152563 0.8720430147331015


In [16]:
gb.fit(train_input, train_target)
gb.feature_importances_

array([0.11949941, 0.74871836, 0.13178224])

In [17]:
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(
    hgb, train_input, train_target, return_train_score=True, n_jobs=-1
)

print(np.mean(scores["train_score"]), np.mean(scores["test_score"]))

0.9321723946453317 0.8801241948619236


In [18]:
%pip install xgboost
from xgboost import XGBClassifier

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.9/253.9 MB 1.5 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [19]:
xgb = XGBClassifier(tree_method="hist", random_state=42)
scores = cross_validate(
    xgb, train_input, train_target, return_train_score=True, n_jobs=-1
)

print(np.mean(scores["train_score"]), np.mean(scores["test_score"]))

0.9567059184812372 0.8783915747390243
